### ISSUE TITLE
Latest Version No Longer Works with Melon Loader, would result in Error

### ISSUE THREAD

**Issue by takdes** [YusufOzmen01/desktopmate-custom-avatar-loader#85]
Many Users Report the same

no longer works with Desktop mate as of latest version

needs an update please
https://steamcommunity.com/app/3301060/discussions/1/594014141938665356/

**Comment by Uggun** [comment]
For now I used depot downloader to downgrade desktop mate to a previous version

**Comment by PineCone69420** [comment]
You'll need to downgrade your Desktop Mate version till this gets fixed by Melon Loader (assuming they will even fix it lol)

You need to use the Steam Console to achieve this. 

First, close Desktop Mate if its open. That error that pops up has to go away. Then Right Click on Desktop Mate, then click on Properties

On the left hand side of the window that opens, you should see a tab called "Updates". Click on it. Then where it says "Automatic Updates" make sure its set to "Wait until I launch the game" (There's no 'never update' so this is the next best thing.'

While you're here, click on "Installed Files" and find a button called "Browse". Click on it. A Windows Explorer window will open to the install directory of Desktop Mate. You'll need this for when you copy the old version back to the new version.

Press your Windows Key + R to open the Run Dialog. Then copy and paste the following command: `steam://open/console`

Your steam window should now have a CONSOLE tab appear. Click on it and type this command `download_depot 3301060 3301061 8228098102537752112`

This will download the older version of Desktop Mate that was working with MelonLoader.

The console will alert you when it has finished, and where it downloaded the application to. You can use the Run Dialog to get there, or use Windows Explorer to manually go to the path specified on the console window, then copy & paste over your existing Desktop Mate install. (I chose to delete and then paste it. I had to re-install Melon Loader but I'd rather be safe than sorry)

I would strongly suggest making a copy of the older version, incase steam downloads the latest one without asking. If it does update, you can just overwrite it with the old version.

Remember the Explorer window you opened to your Desktop Mate installation? Open that and paste the files you copied earlier to this folder.

If Desktop Mate isn't working how you expect it to, I would suggest deleting everything and then paste again. This WILL delete MelonLoader & the Custom Avatar Mod, so you will need to install those again.

When I tried this, the first time I opened the older version, it chewed about 3 GB of RAM and was stick for about a minute. Then it loaded the default avatar and I had to close it, and open it again for it to chew around 300MB of RAM.

**Comment by paranoi-a-39** [comment]
is there a way of downgrading without losing miku dlc? the option still appears but when i try to change the default girl pops back up

**Comment by PineCone69420** [comment]
> is there a way of downgrading without losing miku dlc? the option still appears but when i try to change the default girl pops back up

I don't know how DLC works, but I assume that it won't work with older versions of a game due to Steam's DRM. If anyone has a better understanding of how DLC works & a solution, feel free to chime in and correct me.

**Comment by Uggun** [comment]
> is there a way of downgrading without losing miku dlc? the option still appears but when i try to change the default girl pops back up

You can get the dlc working, by getting it with "other" means, if you catch my drift.

**Comment by SleepyPrince** [comment]
MelonLoader has been updated to [v0.7.0](https://github.com/LavaGang/MelonLoader/releases/tag/v0.7.0), Desktop Mate doesn't crash now but F4 does not open the dialog.
Just checked the MelonLoader log and got this:
`[MelonLoader.Bootstrap] Current game runtime is not supported. The game might have a modified runtime or is not a real Unity game.`

**Comment by Bean-P** [comment]
> You'll need to downgrade your Desktop Mate version till this gets fixed by Melon Loader (assuming they will even fix it lol)
> 
> You need to use the Steam Console to achieve this.
> 
> First, close Desktop Mate if its open. That error that pops up has to go away. Then Right Click on Desktop Mate, then click on Properties
> 
> On the left hand side of the window that opens, you should see a tab called "Updates". Click on it. Then where it says "Automatic Updates" make sure its set to "Wait until I launch the game" (There's no 'never update' so this is the next best thing.'
> 
> While you're here, click on "Installed Files" and find a button called "Browse". Click on it. A Windows Explorer window will open to the install directory of Desktop Mate. You'll need this for when you copy the old version back to the new version.
> 
> Press your Windows Key + R to open the Run Dialog. Then copy and paste the following command: `steam://open/console`
> 
> Your steam window should now have a CONSOLE tab appear. Click on it and type this command `download_depot 3301060 3301061 8228098102537752112`
> 
> This will download the older version of Desktop Mate that was working with MelonLoader.
> 
> The console will alert you when it has finished, and where it downloaded the application to. You can use the Run Dialog to get there, or use Windows Explorer to manually go to the path specified on the console window, then copy & paste over your existing Desktop Mate install. (I chose to delete and then paste it. I had to re-install Melon Loader but I'd rather be safe than sorry)
> 
> I would strongly suggest making a copy of the older version, incase steam downloads the latest one without asking. If it does update, you can just overwrite it with the old version.
> 
> Remember the Explorer window you opened to your Desktop Mate installation? Open that and paste the files you copied earlier to this folder.
> 
> If Desktop Mate isn't working how you expect it to, I would suggest deleting everything and then paste again. This WILL delete MelonLoader & the Custom Avatar Mod, so you will need to install those again.
> 
> When I tried this, the first time I opened the older version, it chewed about 3 GB of RAM and was stick for about a minute. Then it loaded the default avatar and I had to close it, and open it again for it to chew around 300MB of RAM.

It won't let me because I have a family account thing and says I'm underage, I would love to mod DeskMate though, so is there ANY thing else?

**Comment by RisingFog** [comment]
> It won't let me because I have a family account thing and says I'm underage, I would love to mod DeskMate though, so is there ANY thing else?

You can try DepotDownloader and see if you can grab the files that way.

Additionally, make sure that you make appmanifest_3301060.acf read-only in the steamapps folder to prevent the game from auto-updating.

**Comment by Uggun** [comment]
> It won't let me because I have a family account thing and says I'm underage, I would love to mod DeskMate though, so is there ANY thing else?

What part is it not letting you? If you can't do it with the steam console, try downloading with the depot downloader from github like I did. There's plenty of tutorials, I picked the first one that popped up when searching how to downgrade games on steam and figured it out. An example of how the command would look like: "C:\Users\User\Downloads\DepotDownloader-windows-x64\DepotDownloader.exe" depotdownloader -app 3301060 -depot 3301061 -manifest 8228098102537752112 -username -password       . Just copy everything into cmd or whatever and replace with the correct location of where you extracted your downloader, then enter your username and password. You'll have you use authenticator to confirm it's you and it should work.

**Comment by Bean-P** [comment]
> > It won't let me because I have a family account thing and says I'm underage, I would love to mod DeskMate though, so is there ANY thing else?
> 
> What part is it not letting you? If you can't do it with the steam console, try downloading with the depot downloader from github like I did. There's plenty of tutorials, I picked the first one that popped up when searching how to downgrade games on steam and figured it out. An example of how the command would look like: "C:\Users\User\Downloads\DepotDownloader-windows-x64\DepotDownloader.exe" depotdownloader -app 3301060 -depot 3301061 -manifest 8228098102537752112 -username -password . Just copy everything into cmd or whatever and replace with the correct location of where you extracted your downloader, then enter your username and password. You'll have you use authenticator to confirm it's you and it should work.

Ok! Thank you I'll try!!!

**Comment by kairusds** [comment]
Used DepotDownloader to download older versions, including the first version of the app and it just launches Steam for me, prompting me to update it.

**Comment by Malkybutt** [comment]
> Used DepotDownloader to download older versions, including the first version of the app and it just launches Steam for me, prompting me to update it.

You need to set manifest to read-only

**Comment by kairusds** [comment]
> > Used DepotDownloader to download older versions, including the first version of the app and it just launches Steam for me, prompting me to update it.
> 
> You need to set manifest to read-only

you mean `-manifest-only`?

**Comment by roctaiwan5** [comment]
it worked after i download the old version, but now it says that "Failed to initialize MelonLoader: Failed to get function pointer: il2cpp_init"

**Comment by kairusds** [comment]
> it worked after i download the old version, but now it says that "Failed to initialize MelonLoader: Failed to get function pointer: il2cpp_init"

reinstall melonloader and refer to this https://github.com/YusufOzmen01/desktopmate-custom-avatar-loader/issues/85#issuecomment-2635622426

**Comment by roctaiwan5** [comment]
i upgrade melonloader to v0.7.0 but now i can't change it's model by pressing F4

**Comment by kairusds** [comment]
> i upgrade melonloader to v0.7.0 but now i can't change it's model by pressing F4

the recommended version is 0.6.6 as stated on the readme

**Comment by Uggun** [comment]
> i upgrade melonloader to v0.7.0 but now i can't change it's model by pressing F4

IDK v0.7.0 works just fine for me

**Comment by Malkybutt** [comment]
You can also use the steam_appid.txt trick and launch the game from the downgraded folder so it won't prompt steam no more

**Comment by hijoem** [comment]
> You can also use the steam_appid.txt trick and launch the game from the downgraded folder so it won't prompt steam no more
please elaborate

**Comment by hijoem** [comment]
> You can also use the steam_appid.txt trick and launch the game from the downgraded folder so it won't prompt steam no more

Elaborate please

**Comment by Malkybutt** [comment]
Downgrade your app as described by @jose011974 and change the folder name to anythign but the original one. Then in the root of the downgraded folder add this txt file to "fool" Steam (I advise uninstalling Desktop Mate via Steam if it gives you weird conflicts and to run the older version from the .exe file)

[steam_appid.txt](https://github.com/user-attachments/files/18811953/steam_appid.txt)


> You'll need to downgrade your Desktop Mate version till this gets fixed by Melon Loader (assuming they will even fix it lol)
> 
> You need to use the Steam Console to achieve this.
> 
> First, close Desktop Mate if its open. That error that pops up has to go away. Then Right Click on Desktop Mate, then click on Properties
> 
> On the left hand side of the window that opens, you should see a tab called "Updates". Click on it. Then where it says "Automatic Updates" make sure its set to "Wait until I launch the game" (There's no 'never update' so this is the next best thing.'
> 
> While you're here, click on "Installed Files" and find a button called "Browse". Click on it. A Windows Explorer window will open to the install directory of Desktop Mate. You'll need this for when you copy the old version back to the new version.
> 
> Press your Windows Key + R to open the Run Dialog. Then copy and paste the following command: `steam://open/console`
> 
> Your steam window should now have a CONSOLE tab appear. Click on it and type this command `download_depot 3301060 3301061 8228098102537752112`
> 
> This will download the older version of Desktop Mate that was working with MelonLoader.
> 
> The console will alert you when it has finished, and where it downloaded the application to. You can use the Run Dialog to get there, or use Windows Explorer to manually go to the path specified on the console window, then copy & paste over your existing Desktop Mate install. (I chose to delete and then paste it. I had to re-install Melon Loader but I'd rather be safe than sorry)
> 
> I would strongly suggest making a copy of the older version, incase steam downloads the latest one without asking. If it does update, you can just overwrite it with the old version.
> 
> Remember the Explorer window you opened to your Desktop Mate installation? Open that and paste the files you copied earlier to this folder.
> 
> If Desktop Mate isn't working how you expect it to, I would suggest deleting everything and then paste again. This WILL delete MelonLoader & the Custom Avatar Mod, so you will need to install those again.
> 
> When I tried this, the first time I opened the older version, it chewed about 3 GB of RAM and was stick for about a minute. Then it loaded the default avatar and I had to close it, and open it again for it to chew around 300MB of RAM.

**Comment by Lordgeorge16** [comment]
Instead of jumping through all of these hoops to downgrade your game, downgrade your Melon Launcher, etc, why doesn't the mod author just update the mod to make it compatible with the latest versions of these programs?  Are they no longer active on Github?

EDIT: I see the issue now - people online are saying that the devs killed all modding support.  That really sucks.  They wouldn't have had to do that in the first place if they'd just let us import our own characters for free without using mods.  It's not like Desktop Mate was going to be a massive commercial success or anything, just a fun little thing to have playing in the background while you do other stuff.

**Comment by ethanaobrien** [comment]
> You'll need to downgrade your Desktop Mate version till this gets fixed by Melon Loader (assuming they will even fix it lol)
> 
> You need to use the Steam Console to achieve this.
> 
> First, close Desktop Mate if its open. That error that pops up has to go away. Then Right Click on Desktop Mate, then click on Properties
> 
> etc etc etc... message clipped 

To add to this, if you want to **completely** remove the need for steam (running on a pc without steam, or without steam in the background) you can use the [goldberg_emulator](https://mr_goldberg.gitlab.io/goldberg_emulator/)

Just download the latest release from the link, and replace `DesktopMate_Data\Plugins\x86_64\steam_api64.dll` with `steam_api64.dll` from the release (or `experimental/steam_api64.dll` should work too - this basically revokes internet access)

I have been using this method to run it since the inital desktopmate release. I would share my backups, but I probably shouldnt

**Comment by kairusds** [comment]
> > You'll need to downgrade your Desktop Mate version till this gets fixed by Melon Loader (assuming they will even fix it lol)
> > You need to use the Steam Console to achieve this.
> > First, close Desktop Mate if its open. That error that pops up has to go away. Then Right Click on Desktop Mate, then click on Properties
> > etc etc etc... message clipped
> 
> To add to this, if you want to **completely** remove the need for steam (running on a pc without steam, or without steam in the background) you can use the [goldberg_emulator](https://mr_goldberg.gitlab.io/goldberg_emulator/)
> 
> Just download the latest release from the link, and replace `DesktopMate_Data\Plugins\x86_64\steam_api64.dll` with `steam_api64.dll` from the release (or `experimental/steam_api64.dll` should work too - this basically revokes internet access)
> 
> I have been using this method to run it since the inital desktopmate release. I would share my backups, but I probably shouldnt

To add to this, the [fork](https://github.com/Detanup01/gbe_fork) is useful if the original goldberg stops working for DesktopMate since it's constantly updated.

**Comment by Ravendwyr** [comment]
![Image](https://github.com/user-attachments/assets/c3fc1a5b-87c5-4217-ac0a-8fb717824ab9)
Might be worth noting here... Desktop Mate's 1.3.0 changelog teases a "VRM file import function" might be in the works.

**Comment by Wicked-Vill** [comment]
https://www.youtube.com/watch?v=iS47dIU38JE here's a tutorial video for downgrading desktop mate and preventing it from updating itself
